# to delete existing environment
# conda env remove --name ecgtl
# 
# to create new environment
# conda env create -f environment.yml
# 
# to update:
# conda env update -f environment.yml
name: ecgtl
dependencies:
  - python=3.10
  - tensorflow
  - h5py
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tqdm
  - wfdb